# Generated by Django 4.2 on 2024-12-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_member_groups_member_is_superuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
